### ISSUE TITLE
Is this package alive?

### ISSUE THREAD

**Issue by csaundersz** [awaragi/mocha-testrail-reporter#22]
All code was deleted from master in https://github.com/awaragi/mocha-testrail-reporter/commit/8a12765f5e10ef4fe9432bda07efbb2fadd75cec but the commit message doesn't align with the change.

Does this imply the project is no longer being maintained?

**Comment by awaragi** [comment]
not sure what happened. I dont know why the main code was deleted. I will try to fix it when I have some free time (family and work ....).

**Comment by awaragi** [comment]
reverted the delete commit. not sure what happened.
